import os

OPEN_AI_API_KEY = os.environ.get("OPEN_AI_API_KEY")
SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN")
DEFAULT_CHAT_GPT_MODEL = "gpt-3.5-turbo"
DEFAULT_CHAT_GPT_MAX_TOKENS = 3500
MAX_REPLIES = 7
